using System;
using System.Collections.Generic;
using System.Text;

namespace BlazorAgGrid
{

    /// Row Object(aka Row Node)
    ///    https://www.ag-grid.com/javascript-grid-row-node/#row-object-aka-row-node
    /// A Row Node represents one row of data.The Row Node will
    /// contain a reference to the data item your application
    /// provided as well as other runtime information about the
    /// row. The Row Node contains attributes, methods and emits
    /// events. Additional attributes are used if the Row Node is
    /// a group.
    public class RowNode
    {
        /// Unique ID for the node. Either provided by the
        /// application, or generated by the grid if not.
        public string Id { get; set; }
        /// The data as provided by the application.
        public object Data { get; set; }
        /// The parent node to this node, or empty if top level.
        public RowNode Parent { get; set; }
        /// How many levels this node is from the top when grouping.
        public int Level { get; set; }
        /// How many levels this node is from the top when grouping
        /// in the UI (only different to 'parent' when property
        /// groupRemoveSingleChildren= true.
        public int UiLevel { get; set; }
        /// True if this node is a group node (ie has children).
        public bool Group { get; set; }
        /// top' or 'bottom' if pinned row, otherwise null or
        /// undefined.
        public string RowPinned { get; set; }
        /// True if this node can flower (ie can be expanded, but
        /// has no direct children).
        public bool CanFlower { get; set; }
        /// The child flower of this node.
        public string ChildFlower { get; set; }
        /// Index of this row with respect to it's parent when
        /// grouping. Changes when data is sorted.
        public int ChildIndex { get; set; }
        /// True if this is the first child in this group.
        /// Changes when data is sorted.
        public bool FirstChild { get; set; }
        /// True if this is the last child in this group.
        /// Changes when data is sorted.
        public bool LastChild { get; set; }
        /// Used by enterprise row model, true if this row
        /// node is a stub. A stub is a placeholder row with
        /// loading icon while waiting from row to be loaded.
        public bool Stub { get; set; }
        /// The row height in pixels.
        public int RowHeight { get; set; }
        /// The row top position in pixels.
        public int RowTop { get; set; }
        /// If using quick filter, stores a string representation
        /// of the row for searching against.
        public string QuickFilterAggregateText { get; set; }

    }
}
